# Generated by Django 3.2 on 2021-09-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=255)),
                ('price', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gateway.account')),
            ],
        ),
    ]
