version: "3.8"

services:
  redis:
    image: "redis"
    command: redis-server --timeout 3000
    ports:
      - "6379:6379"
    volumes:
      - ../:/app

  migrations:
    build: .
    command: python3 manage.py migrate
    volumes:
      - ../:/app
    depends_on:
      - redis

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_URL=redis
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

